# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-16 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='site_contact',
            field=models.TextField(default='', verbose_name='contact Me'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='site_links',
            field=models.TextField(default='', verbose_name='links'),
        ),
    ]
