# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-17 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190416_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acimage',
            name='image_path',
            field=models.ImageField(upload_to='upload/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(upload_to='image/article/', verbose_name='文章配图'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='site_logo',
            field=models.ImageField(upload_to='image/site/', verbose_name='站点logo'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='site_topimage',
            field=models.ImageField(upload_to='image/site/', verbose_name='顶部大图'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(upload_to='image/user/', verbose_name='用户头像'),
        ),
    ]
