# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-17 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190417_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_detail',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='个人简介'),
        ),
    ]
