# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-17 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_userprofile_user_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acimage',
            name='image_path',
            field=models.ImageField(default='upload/default.png', upload_to='upload/%Y/%m', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='image/article/default.png', upload_to='image/article/%Y/%m', verbose_name='文章配图'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='site_logo',
            field=models.ImageField(default='image/site/default.png', upload_to='image/site/', verbose_name='站点logo'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='site_topimage',
            field=models.ImageField(default='image/site/topbg.jpg', upload_to='image/site/', verbose_name='顶部大图'),
        ),
    ]
