# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-08 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190417_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acimage',
            name='image_path',
            field=models.ImageField(default=' ', upload_to='upload/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default=' ', upload_to='image/article/', verbose_name='文章配图'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_original',
            field=models.CharField(choices=[('0', '转载'), ('1', '原创')], default='1', max_length=10, verbose_name='是否原创'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_support',
            field=models.CharField(choices=[('1', '推荐'), ('0', '取消推荐')], default='1', max_length=10, verbose_name='文章推荐'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_up',
            field=models.CharField(choices=[('1', '置顶'), ('0', '取消置顶')], default='1', max_length=10, verbose_name='文章置顶'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='site_logo',
            field=models.ImageField(default=' ', upload_to='image/site/', verbose_name='站点logo'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='site_topimage',
            field=models.ImageField(default=' ', upload_to='image/site/', verbose_name='顶部大图'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(default='', upload_to='image/user/', verbose_name='用户头像'),
        ),
    ]
